services:
  waline:
    image: lizheming/waline:latest
    container_name: waline
    restart: always
    ports:
      - "8365:8360"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_DB=waline
      - MYSQL_USER=waline
      - MYSQL_PASSWORD=CHANGE_ME_WALINE_DB_PASSWORD
      - SITE_URL=https://tangjin.xyz
      - SECURE=false
    extra_hosts:
      - "host.docker.internal:host-gateway"

  umami:
    image: ghcr.io/umami-software/umami:mysql-latest
    container_name: umami
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=mysql://umami:CHANGE_ME_UMAMI_DB_PASSWORD@host.docker.internal:3306/umami
      - DATABASE_TYPE=mysql
      - HASH_SALT=CHANGE_ME_HASH_SALT
    command: ["npm", "run", "start-server"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
